### ISSUE TITLE
Doesn't work in Safari 7.0.5

### ISSUE THREAD

**Issue by zenopopovici** [hashcash/jquery.hashcash.io#1]
I see that the browser is not supported, but it would be nice to know why.

**Comment by hippich** [comment]
In theory it should. I am trying to debug why it is not working. I would say 99% it will work, just need to find a cause. I will keep this issue open to keep track of it.

**Comment by hippich** [comment]
Should be fixed by now. Problem was on hashcash.io side, so no jquery plugin update is required. Please let me know if it works for your after clearing cache and I will close this issue if you confirm it.

**Comment by zenopopovici** [comment]
Works! You can add Safari to supported browsers :)
