### ISSUE TITLE
Makes Safari & Chrome Crash

### ISSUE THREAD

**Issue by zenopopovici** [hashcash/jquery.hashcash.io#2]
When hitting reload (CMD+R) a couple of times, the browser crashes. Happens also on Hashcash.io.

**Comment by hippich** [comment]
Could you give me browses and os versions so I could see if I can replicate it locally?

**Comment by zenopopovici** [comment]
OSX 10.9
Safari 7.0.5
Chrome 35.0.1916.153

**Comment by hippich** [comment]
I know this is silly answer, but "it works on my machine". Here is screencast - http://screencast.com/t/UDULp1kVbnNp

I wonder if some extensions or something in desktop user profile triggers it. Would you mind trying it on another mac or try to create new user account on your mac and see if it still crashes there?
